### PR TITLE
Create header

### PR DESCRIPTION
**Pull request by kimc0de**
Added:
- styles.css
- header.css
- new logos.svg (last ones were with background)
- favicon

Done:
- header.ejs responsive :D

### CODE REVIEW

**Comment by lyrated** [comment]
Hey, I'm reviewing it right now. Looks awesome so far!!

Just on the mobile version, I can't seem to open the navigation. idk if that's only on my computer? Like when I click on the icon, the menu doesn't open...

**Comment by kimc0de** [comment]
@lyrated you're right i forgot to ask.. i had the same problem and still couldnt fix it. the code was from bootstrap.. still working for rematch but no idea why not working for us

**Comment by lyrated** [comment]
@kimc0de oh we haven't put the bootstrap javascript file in our project yet lol. That's most likely the problem here. Just add the bootstrap & jQuery scripts and try again ^^

**Comment by kimc0de** [comment]
@lyrated righttt

**Comment by lyrated** [comment]
grafik

the mobile version looks like this now for me. (Also I liked the old width on the buttons for desktop version :D)

when the menu opened the header also moved a bit up a few pixels

**Review by lyrated — APPROVED** [review]
lovely as always <3

after merge, please check if .idea folder is still there, if yes please delete~

**Pull request merged**
